name: starter_architecture_flutter_firebase
description: A new Flutter project.

publish_to: 'none'
version: 2.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  cloud_firestore: ^4.9.2
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  firebase_auth: ^4.10.0
  firebase_core: ^2.16.0
  firebase_ui_auth: ^1.8.0
  firebase_ui_firestore: ^1.5.11
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.1
  flutter_svg: ^2.0.7
  go_router: 11.1.1
  intl: ^0.18.1
  rxdart: ^0.27.7
  shared_preferences: ^2.2.1
  # the annotation package containing @riverpod
  riverpod_annotation: 2.1.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  random_string: ^2.3.1
  flutter_lints: ^2.0.3
  # a tool for running code generators
  build_runner: ^2.4.6
  # the code generator
  riverpod_generator: 2.3.3
  # riverpod_lint makes it easier to work with Riverpod
  riverpod_lint: 2.1.1
  # import custom_lint too as riverpod_lint depends on it
  custom_lint: 0.5.3
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/time-tracking.svg
